if(EXISTS "/home/liu/bustub-private/build-release/test/hash_table_test[1]_tests.cmake")
  include("/home/liu/bustub-private/build-release/test/hash_table_test[1]_tests.cmake")
else()
  add_test(hash_table_test_NOT_BUILT hash_table_test_NOT_BUILT)
endif()
