if(EXISTS "/home/liu/bustub-private/build-release/test/lru_replacer_test[1]_tests.cmake")
  include("/home/liu/bustub-private/build-release/test/lru_replacer_test[1]_tests.cmake")
else()
  add_test(lru_replacer_test_NOT_BUILT lru_replacer_test_NOT_BUILT)
endif()
