if(EXISTS "/home/liu/bustub-private/build-release/test/recovery_test[1]_tests.cmake")
  include("/home/liu/bustub-private/build-release/test/recovery_test[1]_tests.cmake")
else()
  add_test(recovery_test_NOT_BUILT recovery_test_NOT_BUILT)
endif()
