if(EXISTS "/home/liu/bustub-private/build-release/test/transaction_test[1]_tests.cmake")
  include("/home/liu/bustub-private/build-release/test/transaction_test[1]_tests.cmake")
else()
  add_test(transaction_test_NOT_BUILT transaction_test_NOT_BUILT)
endif()
